spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  database:
    driverClassName: org.postgresql.Driver

---

spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:postgresql://mircle.cbmwsuphlpqy.ap-southeast-2.rds.amazonaws.com:5432/mircle
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

---

spring:
  profiles: test
  jpa:
    database: platform
    show-sql: true
    hibernate:
      ddl-auto: create
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:postgresql://mircle.cbmwsuphlpqy.ap-southeast-2.rds.amazonaws.com:5432/mircle
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

---

spring:
  profiles: prod
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:postgresql://mircle.cbmwsuphlpqy.ap-southeast-2.rds.amazonaws.com:5432/mircle
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}