spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    # database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  database:
    driverClassName: org.h2.Driver
  datasource:
    platform: h2
    url: jdbc:h2:file:~/test
    username: sa
    password:

---

spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:${DATABASE_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  server:
    port: 80

---

spring:
  profiles: prod
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:${HEROKU_POSTGRESQL_GREEN_URL}
    username: ${PROD_POSTGRESQL_USERNAME}
    password: ${PROD_POSTGRESQL_PASSWORD}
  server:
    port: 80